### ISSUE TITLE
The triggersOnUpdate test should verify specific values

### ISSUE THREAD

**Issue by npace** [alexfu/Phoenix#1]
[This test](https://github.com/alexfu/Phoenix/blob/master/library/src/test/java/com/alexfu/phoenix/PhoenixTests.java#L61) should be asserting that the app went from version 1 to version 2.
The verification part should instead be something similar to this:
 `Mockito.verify(callback, times(1)).onUpdate(eq(1), eq(2));`

**Comment by alexfu** [comment]
@npace Thank you. Your suggestion should probably be in it's own test since the once you referenced is already testing the update logic. I'd like to have each test be testing a single aspect.

**Comment by npace** [comment]
Thanks for humoring my humble nit-pick.
I would argue that this exact same test should assert over the values `(eq(1), eq(2))` since 1 and 2 are already being used [here](https://github.com/alexfu/Phoenix/blob/master/library/src/test/java/com/alexfu/phoenix/PhoenixTests.java#L63) and [here](https://github.com/alexfu/Phoenix/blob/master/library/src/test/java/com/alexfu/phoenix/PhoenixTests.java#L65).

As it's currently being implemented, this test would pass even if your callback is invoked with the values 1337 and 9001 for example, even though you arrange it to use 1 and 2. I admit that this is not a very likely scenario given that the library is small and focused, but technically this test can give you false positives.

**Comment by alexfu** [comment]
> I would argue that this exact same test should assert over the values `(eq(1), eq(2))` since 1 and 2 are already being used [here](https://github.com/alexfu/Phoenix/blob/master/library/src/test/java/com/alexfu/phoenix/PhoenixTests.java#L63) and [here](https://github.com/alexfu/Phoenix/blob/master/library/src/test/java/com/alexfu/phoenix/PhoenixTests.java#L65).

Good point.
